#ifndef NORMAL_DISTRIBUTION_LD_HPP
#define NORMA_DISTRIBUTION_LD_HPP
#include <iostream>
#include <cmath>
#include <climits>
#include <list>
#include <vector>
#include <algorithm>
#include <numeric>
#include <gsl/gsl_qrng.h>
